---
title: "Energy Related Data Sources"
description: "Links to Renewable Energy related web pages."
date: "2020-03-28"
categories: [energy, data-sources]
toc: true
---

In this entry information related with Energy Markets, Flows, etc is gathered.

## TSO's and Electrical Markets

### [Red Electrica de España (REE)](https://www.ree.es/en)

They have a [powerful API](https://www.ree.es/es/apidatos#) wich can be used to retrieve a lot of information about Spanish electricity system operation and transport.

### [ENTSO-E](https://www.entsoe.eu)

ENTSO-E, the European Network of Transmission System Operators for Electricity, represents 42 electricity transmission system operators (TSOs) from 35 countries across Europe. ENTSO-E was established and given legal mandates by the EU’s Third Legislative Package for the Internal Energy Market in 2009, which aims at further liberalising the gas and electricity markets in the EU.

The role of Transmission System Operators has considerably evolved with the Third Energy Package. Due to unbundling and the liberalisation of the energy market TSOs have become the meeting place for the various players to interact on the market place.

## Renewable Energy Data

### PV Data

#### PVOutput ([https://pvoutput.org/](https://pvoutput.org/))

Historical solar photovoltaic data. The aim is to provide both a Python library for interacting with [PVOutput.org's API](https://pvoutput.org/help.html#api), and a set of scripts for downloading lots of data.

## Weather Data Sources

### NOAA's GFS

* [S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/noaa-gfs-bdp-pds/?region=us-east-1&tab=overview)
* [Nomads Server](https://nomads.ncep.noaa.gov/)

### MetOffice

* [S3 bucket (24h delay)](https://registry.opendata.aws/uk-met-office/)

### Meteo France

* [Météo-France models on AWS](https://mf-models-on-aws.org/)

### Era 5 (Reanalysis data)

* [ERA5 API](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form)

## Electric Consumption data


### UK Domestic Appliance-Level Electricity (UK-DALE) dataset

This [dataset](https://jack-kelly.com/data/) records the power demand from five houses. In each house we record both the whole-house mains power demand every six seconds as well as power demand from individual appliances every six seconds. In three of the five houses (houses 1, 2 and 5) we also record the whole-house voltage and current at 16 kHz.



## Repositories

### [Open Climate Fix](https://github.com/openclimatefix): Mostly developed by Jack Kelly

## Packages 

### Python

#### [PVlib (Python)](https://pvlib-python.readthedocs.io/en/stable/)

PVlib (Python) is a library developed by Sandia Laboratories designed for simulating the performance of photovoltaic energy systems.
